### ISSUE TITLE
bandwidth_test issue

### ISSUE THREAD

**Issue by tuanha-viosoft** [Derecho-Project/derecho-unified#81] opened 2018-11-30 08:28 UTC
I run bandwidth_test with 2 nodes, num_senders_selector=0, num_messages={1, 10, 100}, delivery_mode=0, msg_size={64, 128, 256, 512, 1024, 10240, 1000000}.
Total test times: 210, Failed: 80, although "data_derecho_bw" was created.
Error log:
`Exception in the failure upcall: Potential partitioning event: this node is no longer in the majority and must shut down!
Exception in the SST detect thread: Potential partitioning event: this node is no longer in the majority and must shut down!`
`Poll completion error with node (id=1). Freezing row 1
Exception in the failure upcall: Potential partitioning event: this node is no longer in the majority and must shut down!`

When I increase num_nodes to 5, new error log appeared:
`[140737144416000] polling thread starts.
Initialized SST and Started Threads
Initialization complete
Finished constructing/joining GroupThe persist thread started

The order of members is :
0 1 2 3 4
Initialized SST and Started Threads
DerechoGroup send thread shutting down
The persist thread is exiting
timeout_thread shutting down
/root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
/root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
/root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
/root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
/root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
/root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
/root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
/root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
/root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
/root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.`

When I increase num_nodes to 40, the performance test couldn't be finished
`[140737144416000] polling thread starts.
Initialized SST and Started Threads
Initialization complete
Reporting failure on row 12 due to a missing poll completion
Reporting failure on row 19 due to a missing poll completion
Reporting failure on row 20 due to a missing poll completion
Reporting failure on row 31 due to a missing poll completion
Reporting failure on row 12 due to a missing poll completion
Reporting failure on row 19 due to a missing poll completion
Reporting failure on row 20 due to a missing poll completion
Reporting failure on row 31 due to a missing poll completion
Reporting failure on row 12 due to a missing poll completion
Reporting failure on row 19 due to a missing poll completion
Reporting failure on row 20 due to a missing poll completion`

I would like to make a stable Group (includes thousands of nodes), can you tell me how to resolve this issue?

**Comment by tuanha-viosoft** [comment] 2018-12-01 01:52
Message size means MAX_PAYLOAD_SIZE. I changed it in derecho.cfg file

**Comment by sagarjha** [comment] 2018-12-01 03:31
Yes, we have two message size parameters in the config file: `max_payload_size` and `max_smc_payload_size`. The second parameter uses a specialized protocol that is more suitable for small messages. If you are working with a message size less than 15 KBs, it might be best to set the `max_smc_payload_size` to that value (in that case both parameters will have the same value). If you are also sending very large messages, `max_payload_size` will have a higher value than `max_smc_payload_size`.

**Comment by tuanha-viosoft** [comment] 2018-12-03 02:19
@sagarjha I tried to set `max_smc_payload_size` and `max_payload_size` the same value, but still got the error message.

**Comment by KenBirman** [comment] 2018-12-03 02:52
Please try and answer all the questions Weijia asked, one by one.

**Comment by sagarjha** [comment] 2018-12-03 03:02
Yes, please try Weijia's suggestions. You can post an image of the run on two nodes first. We can go through that.
Also, the test writes data to a file called `data_derecho_bw` in the same directory as the executable. You can check if the file was created by the test.

**Comment by tuanha-viosoft** [comment] 2018-12-03 03:31
This is the log file when I run test 210 times.
[log.txt](https://github.com/Derecho-Project/derecho-unified/files/2637963/log.txt)

**Comment by songweijia** [comment] 2018-12-03 03:58
I think the result looks normal to me, as what @sagarjha confirmed. Please ignore the exception message. This is because one node quits a little bit earlier than the other node, which is detected by the other node.

Btw, I'm interested in the performance data as well as your environment. It would be great if you can show us the contents of `data_derecho_log`.

**Comment by tuanha-viosoft** [comment] 2018-12-03 04:08
@songweijia here is the `data_derecho_bw` result
[data_derecho_bw.txt](https://github.com/Derecho-Project/derecho-unified/files/2638027/data_derecho_bw.txt)

Btw, When I increase num_nodes to 5, I got new error log:

> [140737144416000] polling thread starts.
> Initialized SST and Started Threads
> Initialization complete
> Finished constructing/joining GroupThe persist thread started
> 
> The order of members is :
> 0 1 2 3 4
> Initialized SST and Started Threads
> DerechoGroup send thread shutting down
> The persist thread is exiting
> timeout_thread shutting down
> /root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /root/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /root/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.

And when I increase num_nodes to 40, the `data_derecho_bw` can not be created. And I got these error messages:

> Reporting failure on row 12 due to a missing poll completion
> Reporting failure on row 19 due to a missing poll completion 
> Reporting failure on row 20 due to a missing poll completion 
> Reporting failure on row 31 due to a missing poll completion 
> Reporting failure on row 12 due to a missing poll completion 
> Reporting failure on row 19 due to a missing poll completion 
> Reporting failure on row 20 due to a missing poll completion 
> Reporting failure on row 31 due to a missing poll completion 
> Reporting failure on row 12 due to a missing poll completion 
> Reporting failure on row 19 due to a missing poll completion 
> Reporting failure on row 20 due to a missing poll completion

Are they normal cases?

**Comment by songweijia** [comment] 2018-12-03 04:33
@tuanha-viosoft I do find some abnormal data in your result. My first suggestion is to use at least 1000 messages to get a stable throughput evaluation. 

The new exception suggests that some resource is missing when sending a message. Can I know more about your test environment and configuration? Are you running experiments with sockets or RDMA? Can I have a look at your derecho.cfg file?

**Comment by tuanha-viosoft** [comment] 2018-12-03 04:45
This is the result when I run with 1000 messages, 2 nodes.
[data_derecho_bw.txt](https://github.com/Derecho-Project/derecho-unified/files/2638090/data_derecho_bw.txt)
These are the config file of leader node and normal node:

[derecho-leader.cfg.txt](https://github.com/Derecho-Project/derecho-unified/files/2638098/derecho-leader.cfg.txt)
[derecho.cfg.txt](https://github.com/Derecho-Project/derecho-unified/files/2638099/derecho.cfg.txt)

**Comment by songweijia** [comment] 2018-12-03 05:12
Now the two node results make sense to me. 

I'm trying to replicate your issue. Can you answer the following questions?
For the leader node, are you running it in docker containers? If yes, can you let me know 
- how many containers are you running with one server,
- the hardware configuration of the server, like CPU type, memory size.
- can you also try the commands `ulimit -Hn` and .`ulimmit -Sn` inside the container?

**Comment by tuanha-viosoft** [comment] 2018-12-03 05:34
> For the leader node, are you running it in docker containers? If yes, can you let me know

Both leader node and normal node are running in docker containers.

> how many containers are you running with one server,

Depend on test cases, for example, I run 2 nodes on 2 containers, or 5 nodes on 5 containers.

> the hardware configuration of the server, like CPU type, memory size.

CPU: Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz, 32 cores
RAM: 128GB
OS: Ubuntu 16.04

> can you also try the commands ulimit -Hn and .ulimmit -Sn inside the container?

`# ulimit -Hn`
`1048576`
`# ulimit -Sn`
`1048576`
`# ulimit -l`
`unlimited`

**Comment by songweijia** [comment] 2018-12-03 05:38
Thanks! I will try to replicate your experiment and see If I can reproduce your issue.

**Comment by tuanha-viosoft** [comment] 2018-12-03 09:20
I run test with 40 nodes, 1000 messages in Debug mode and got the error log as below
[derecho_debug_log.txt](https://github.com/Derecho-Project/derecho-unified/files/2638789/derecho_debug_log.txt)

**Comment by KenBirman** [comment] 2018-12-03 13:18
You are jumping too quickly to 1000 nodes.  In prior experiments at large scale we only ran on one platform, an HPC computer where we ran in dedicated bare-metal nodes.

To help you with this setup, we need to know the actual runtime environment, including wha else might be on these machines and how you launch the 1000 node containerized setup. Where are the log files being saved?  They need to be in a local file system, not the global file system.  How many physical nodes do the containers run on?

Some file systems have performance issues if 1000 programs launch simultaneously and start opening files and writing them, almost in sync to the millisecond.  This isn’t a behavior global file systems are designed to support.  Even TCP can malfunction at that scale, with every process trying to make and use thousands of TCP connections.  Our prior very large experiments only used RDMA, but RDMA may not be available in your container setting, and even if it is, probably doesn’t support large numbers of containers using it on  any single machine.  Container multitenancy could cause a crash.

But then I would slow down and launch and measure at scale 10 nodes, 50, 100, ... by 50’s.  At what scale do these new timeouts and file system errors suddenly occur?  

So I’m happy that we should help you get this up and running at the largest scale possible.

**Comment by KenBirman** [comment] 2018-12-03 14:11
PS: We are committed to supporting Derecho with RDMA on 1000 (or even more) physical nodes, one application instance per node.  On a machine that actually allows some small number K of applications to share an RDMA NIC, we would even be happy to help get things working with k*1000's of group members... eventually.

But we view it as highly experimental to run with TCP on more than 16-32 nodes (we do want to scale over TCP, but it will take time), and it is not wise to try and run 1000 Derecho application instances on, for example, 2 AWS servers.  That would never work, due to timeouts, and we will not try to support that sort of thing: it would be a waste of our time...  

Additionally, it is important for you as the developer to realize that launching on 1000 physical nodes is hard, and you will spend days or weeks before this is fully stable.  Once Derecho is up and running, you depend only on our layers and those are designed to work at large scale.  But Linux is not designed to boot an application with 1000 members all of which make connections to one-another (so you get 1,000,000 connections right as it starts), plus the file system issues mentioned above.  Linux isn't normally exposed to this sort of nearly simultaneous burst of load.  Thus, Linux can be overwhelmed.

Even on HPC systems, which can support MPI at that scale, because MPI doesn't use an all-to-all connection pattern, we have seen these kinds of difficulties at massive scale.  In MPI there is one leader and N-1 followers, so the primary pattern that arises is really 1-N connections (more accurately, they do have some cases at runtime (like AllReduce) that can create K x K patterns.  I don't know how much success those folks have had with K>=1000, though.  My impression is that All Reduce normally runs on a significantly smaller scale.  Other KxK situations on MPI are probably delicate to initialize, too.)

When we did some RDMC experiments on 1000's of nodes at the LLNL supercomputer center, we actually had a special batch script to launch them 50 at a time, and have them connect in batches, to avoid overloading the file system and TCP layer.  

So... this entire concept of Derecho at 1000's of nodes is something we definitely intend to support, in some specific situations where the goal makes sense, the underlying infrastructure should be able to do it, and where we have access to do debugging of our own RDMA layers during the startup.  But this isn't a sensible thing to do as your very first Derecho deployment!

**Comment by KenBirman** [comment] 2018-12-03 15:36
Yes, but if those are perhaps 40 containers on 2 cores on a single server, we might not expect Derecho to be able to run in that mode.

**Comment by tuanha-viosoft** [comment] 2018-12-05 11:39
@songweijia I run the test on real machines, and I got this error with 5 real nodes.

> /home/ubuntu/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:477,ret=-2,fi_writemsg failed.
> /home/ubuntu/derecho-unified/sst/lf.cpp:506,ret=-2,post_remote_write(2) failed.

I run 280 test cases with num_nodes={5, 10}, num_senders_selector=0, num_message={100, 1000}, delivery_mode=0, and message_size={64, 128, 256, 512, 1024, 10240, 1000000}, and got the result:
[data_derecho_bw.txt](https://github.com/Derecho-Project/derecho-unified/files/2648648/data_derecho_bw.txt)

**Comment by KenBirman** [comment] 2018-12-05 16:23
We’ll need to check the root cause.  Sagar explained that these tests do not shut down gracefully.  Did you check to see if the tests finished, and then gave these errors during shutdown?

In fact we do plan to fix the shutdown errors, since they are annoying and cause confusion.  But the thing to understand is that Derecho is about building services that normally would remain active – we aren’t really focused on the idea of a process waking up, joining for a while, and then exiting voluntarily.

But in these particular tests, when the test is finished, the processes running it all exit.  They can’t exit exactly at the same time to the millisecond, so they tend to see each other’s shutdowns in real-time.  Then they throw these exceptions (which the library should suppress, and we will fix it to suppress them).  But as such, they aren’t really errors.  They are just a very clumsy shutdown.

**Comment by sagarjha** [comment] 2018-12-05 17:09
The writemsg failed errors are definitely not because of the graceless shutdown. I am guessing that the processes aren't able to reach everyone using the network provided. But Weijia will know better.

**Comment by viosoft** [comment] 2018-12-06 14:36
New to this thread/Derecho so please pardon the typical beginner's ignorance.   

One of the primary use-cases highlighted, in the Derecho's paper and Prof. Birman's presentation is to enable data replication at the edge of the network.   As IoT devices are ISA-diversed, it would be highly desirable if Derecho's performance and (more importantly) reliability aren't exclusive to devices sporting RDMA-capable NICs.  Thus, we purposed to determine in our experiment the reliability of Derecho when deployed at scale over a network of libfabric/socket clients.

Our setup consists of 30 servers, each with 32 cores / 132GB and dedicated 10Gbs Intel Niantic NIC on the data plane.  The idea is to spawn multiple containers and VMs on each server to closely emulate the performance, behavior, and functionality of different types of IoT devices and workloads.   Orchestration and automation of a large number of virtualized instances are not a problem for us.   However, understanding the tactical challenge with running Derecho in a virtualized setting, we will pivot to a single instance/server for now.

Questions regarding the use of non RDMA platforms: Derecho uses SST for reliable broadcast, and SST relies on a) atomicity of cache line access and b) RDMA's FIFO ordering to update the predicate tables.  This would imply that different mechanism to ensure atomicity and ordering on platform with no RDMA NIC and varying line sizes.  Is this worth doing, and would the end results out perform existing Paxos implementations?

Many thanks for this, and of course for Prof. Birman's contribution to Isis, Horus, ...

@tuanha-viosoft, can you make sure that we're conducting the runs on the data plane NICs instead of the Linux control plane NIC?

**Comment by KenBirman** [comment] 2018-12-06 15:10
Actually, we support a mapping to a pure TCP communication option, with no RDMA hardware or special NICs.  You won’t get the performance Derecho achieves with true RDMA, but by configuring the system to run purely over TCP, you could apply it in your setting.  In fact we anticipate that more and more of our users will start with a pure TCP setup, build their applications and test them, and only will migrate to RDMA hardware acceleration (1) after their solution is reasonably stable, and (2) if RDMA is actually available.  We do think it will gradually become a more and more common hardware option, though.

We definitely are interested in IoT edge computing cases.  If anything, this is our main focus.  But… we were not thinking of putting Derecho on IoT devices per se.  Instead we are thinking of hosting services on, for example, Azure IoT Edge.  Then the sensor devices would talk to these micro-services via TCP.  The services could use Derecho inside the service, but not for those last hops to the IoT devices.  Down the road we have an idea for making those last hops run over RDMA, if the device has an RDMA NIC.  But this application architecture would still treat them as being external clients, not linked directly to Derecho.

So in your setting, you could simulate a million IoT devices if you wish.  But don’t try to run Derecho as if it was linked to the code actually running on the IoT devices.  Use this Azure micro-services model.  (By the way, Azure IoT Edge is an Ubuntu Linux environment, so this isn’t a mysterious or undocumented approach.  Think: “Cluster of Ubuntu systems, running software from a company like Microsoft, and with the sensors talking to the microservers (the “sub-services”) over TCP).  Like Figure 1 in the Derecho paper.

Inside those micro-services, we need speed.  TCP is ok, be we don’t support high-latency TCP links, or slow ones, and we need a good degree of uniformity: all the various direct paths should be more or less similar in speed and performance, and should be pretty fast, not similar in the sense of really slow. Consider using something else, like Zookeeper, if these properties definitely won’t hold.

The caution I’ll express about your current concept is that you talk about launching lots of containers and VMs.  This just won’t work if all of those try to be part of a Derecho group.  We didn’t create Derecho for that sort of heavily virtualized setup, and  Derecho assumes a slow rate of membership changes: maybe once every few minutes or hours, not a membership change every 100ms.  We wouldn’t be able to provide support for the sorts of problems you might manage to trigger in a very weird, unintended setup:  We are busy just dealing with the real target environment the system was created to address.  Anyhow, as I said, there are products like Zookeeper that would definitely be reasonably stable and robust on highly virtualized setups with dozens of co-resident VMs or containers per machine, etc.  So it isn’t really our primary use case (that form of virtualization), many things might timeout (because of contention and scheduling effects), and there are acceptable options with mature user communities.

My advice is to use Derecho only if your architecture matches our model.  So you need to identify a pretty direct one-to-one map from our target environment and goals to your intended use case.  Yes, you might develop in a simplified setting, but don’t put the system under heavy stress in ways that wouldn’t be at all typical in the target environment – you’ll waste your own time, and ours too.

Also, keep in mind that you are using a beta release of what will be v0.9 or something when we release it for public use, probably with Azure IoT as our target.  So right now, using the system requires you to just buckle down and figure things out.  It isn’t as easy to use now as it will be by the time we are up to release v2.0 or something.  But you sound like hardcore systems people.  So maybe this isn’t a surprising warning.

Zookeeper, in contrast, is up around v5.5 or something.  Turnkey, foolproof, widely used.  But painfully slow.

**Closed** 2019-02-01 02:32 UTC
