### ISSUE TITLE
Support "out of band" buffer allocation and a way to multicast such an object

### ISSUE THREAD

**Issue by KenBirman** [Derecho-Project/derecho-unified#119] opened 2019-03-24 14:29 UTC
Currently, our APIs have an upcall that gives a buffer to the user, who then has to fill in the message body and returns control to Derecho, which will send the object.  For cases where data is collected out of band, like via a DMA from a camera, this forces an extra copy on the critical path.

Desired: a way to call Derecho's memory manager to obtain a buffer ahead of time, into which data can be loaded.  Then a second case for our upcall lambda: the current type signature is for a function that takes the buffer as an argument.  The new one would have no argument and would return the buffer that the user wants Derecho to transmit (via std::shared_ptr or even std::unique_ptr).  Ideally it should be done so that no locking is required.

**Comment by sagarjha** [comment] 2019-03-24 14:59
Duplicate of #99. Or at least very similar to it.

**Comment by KenBirman** [comment] 2019-03-24 15:00
Oh, I didn't remember that I had previously posted that.  Sorry!

**Closed by sagarjha** 2019-03-24 14:59 UTC
Labels: derecho, duplicate, enhancement, new feature
