### ISSUE TITLE
Should we provide access to a wrapped user object from Replicated<T>?

### ISSUE THREAD

**Issue by songweijia** [Derecho-Project/derecho-unified#115] opened 2019-03-20 17:58 UTC
Say we have three nodes A, B, and C in a subgroup. If node A needs to access a historic state of version `v`, the only way is to issue an `ordered_query`, which is unnecessarily heavy. One option is allowing a node to send `p2p_query` to itself. We can also try to provide const access to a wrapped user object from the subgroup handle (Replicated<T>). I actually prefer the `p2p_query` to self because it is neat. Access to a wrapped user object may make concurrent access harder to manage.

**Comment by mpmilano** [comment] 2019-03-20 18:27
I think our basic principle is that replicated objects are actual replicas; unless people are abusing P2PSends they should expect that all nodes respond identically to any OrderedQuery.  Since that's our story, it would make sense to allow P2Pqueries to "yourself", corresponding in a read quorum of 1.

**Comment by KenBirman** [comment] 2019-03-20 18:31
I think Weijia wants this to follow a 1:1 mode, so the idea is the same but he wants it to be P2P query (question: if we merged ordered_query into ordered_send, shouldn’t we merge P2P query and P2P send???)

Same principle though: he wants this to work the identical way both when querying a remote shard and when querying your own shard.

**Comment by sagarjha** [comment] 2019-03-20 20:18
I am going to work on allowing `P2P` query to self. Other than that, the answer to the question in the issue is No by consensus.

**Comment by sagarjha** [comment] 2019-03-20 21:14
Tracked in #116

**Closed by sagarjha** 2019-03-20 21:14 UTC
